server:
  port: 8080

spring:
  application:
    name: money-splitter
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "${POSTGRES_URL:jdbc:postgresql://localhost:5432/money-splitter}"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:postgres}"
  liquibase:
    change-log: "classpath:db/postgresql/liquibase/changelog.xml"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true