server:
  port: 8080

spring:
  application:
    name: money-splitter
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/money-splitter"
    username: "postgres"
    password: "postgres"
  liquibase:
    change-log: "classpath:db/postgresql/liquibase/changelog.xml"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true